'use client';

import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import { createClient } from '@/lib/supabase/client';
import { 
  Sparkles, PenLine, Mic, BookOpen, Headphones,
  ArrowRight, Zap, Target, TrendingUp, CheckCircle2,
  Brain, Clock, BarChart3, Shield, Users,
  ChevronDown, Globe, Award, Quote, AlertTriangle
} from 'lucide-react';
import styles from '@/styles/Home.module.scss';

export default function HomePage() {
  const router = useRouter();
  const [mounted, setMounted] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [isAuthenticated, setIsAuthenticated] = useState<boolean | null>(null);

  useEffect(() => {
    createClient().auth.getSession().then(({ data }) => {
      setIsAuthenticated(!!data.session);
    });
  }, []);

  const handleSkillClick = (e: React.MouseEvent, path: string) => {
    if (isAuthenticated === false) {
      e.preventDefault();
      router.push(`/auth/login?redirect=${encodeURIComponent(path)}`);
    }
  };

  useEffect(() => {
    setMounted(true);
  }, []);

  const skills = [
    {
      id: 'writing',
      title: 'Writing',
      desc: 'Email & Survey responses with real-time AI scoring on the 1-12 CELPIP scale',
      icon: PenLine,
      stats: '222+ prompts • AI Scoring',
      path: '/writing',
      free: '3 Task 1 + 3 Task 2 free prompts'
    },
    {
      id: 'speaking',
      title: 'Speaking',
      desc: 'Record yourself, get instant AI analysis with pronunciation & fluency feedback',
      icon: Mic,
      stats: '8 Tasks • Whisper AI',
      path: '/speaking',
      free: '8 free prompts + self-eval checklist'
    },
    {
      id: 'reading',
      title: 'Reading',
      desc: 'Timed passages with authentic exam-style questions across all 4 parts',
      icon: BookOpen,
      stats: '4 Parts • 290+ Passages',
      path: '/reading',
      free: '4 free passages to start'
    },
    {
      id: 'listening',
      title: 'Listening',
      desc: 'One-play audio — just like the real CELPIP test, with 460+ practice passages',
      icon: Headphones,
      stats: '6 Parts • 24 Passages',
      path: '/listening',
      free: '6 free passages + cached audio'
    }
  ];

  const proFeatures = [
    { icon: Brain, title: 'AI Practice Generator', desc: 'Infinite exercises generated by AI, tailored to your level' },
    { icon: TrendingUp, title: 'Adaptive Difficulty', desc: 'Auto-adjusts based on your performance — always in your growth zone' },
    { icon: PenLine, title: 'AI Writing Tutor', desc: 'Detailed grammar, vocabulary & structure feedback on every response' },
    { icon: Mic, title: 'AI Speaking Coach', desc: 'Whisper transcription + GPT analysis of pronunciation, fluency & coherence' },
    { icon: Target, title: 'AI Mock Exam', desc: 'Full simulated CELPIP test with timer, scoring & CLB estimate' },
    { icon: BarChart3, title: 'Weakness Report', desc: 'Per-section breakdown with trends and personalized recommendations' },
  ];

  const comparisons = [
    { feature: 'Practice Questions', us: '1,500+ (infinite with AI)', them: 'Fixed question banks' },
    { feature: 'AI Feedback', us: 'Real-time on Writing & Speaking', them: 'Answer keys only' },
    { feature: 'Adaptive Difficulty', us: '✅ Auto-adjusts to your level', them: '❌ One size fits all' },
    { feature: 'Mock Exam with CLB Estimate', us: '✅ Full simulation', them: '❌ or basic only' },
    { feature: 'Audio Listening Practice', us: '460+ cached + unlimited AI', them: 'Limited passages' },
    { feature: 'Price', us: 'Free tier + CA$29.99/mo Pro', them: '$29-49/month, no free tier' },
  ];

  const faqs = [
    { q: 'Is there really free content?', a: 'Yes! You get free practice in all 4 modules — Writing, Speaking, Reading, and Listening — plus complete technique guides and quizzes. No credit card needed. Upgrade to Pro for unlimited prompts, AI feedback, and advanced features.' },
    { q: 'What does Pro include?', a: 'Pro unlocks AI-powered features: infinite practice exercises, AI Writing Tutor with detailed feedback, AI Speaking Coach with Whisper transcription, Mock Exams with CLB estimates, adaptive difficulty, and weakness reports.' },
    { q: 'Can I cancel anytime?', a: 'Absolutely. Cancel your Pro subscription anytime from your profile. No contracts, no hidden fees. You keep access until the end of your billing period.' },
    { q: 'How is this different from other CELPIP prep sites?', a: 'Most sites offer static question banks. We use AI to generate infinite exercises, give real-time feedback on writing and speaking, and adapt difficulty to your level. Plus our free tier is more generous than competitors\' paid plans.' },
    { q: 'Does it work on mobile?', a: 'Yes! The entire platform is mobile-optimized. Practice on your phone during commute, lunch breaks, or anywhere.' },
    { q: 'I\'m taking CELPIP next week. Can this help?', a: 'Definitely. Start with our Technique Guides for quick strategy tips, then do a Mock Exam to identify weak areas. Even a few days of focused AI practice can improve your score.' },
  ];

  const stats = [
    { value: '3,900+', label: 'Practice Exercises', sub: 'all 4 skills' },
    { value: 'AI', label: 'Instant Feedback', sub: 'writing & speaking' },
    { value: '150+', label: 'Students', sub: 'this month' },
    { value: '9+', label: 'Target Score', sub: 'CLB ready' },
  ];

  const testimonials = [
    {
      quote: 'I was stuck at CLB 7 for 3 tests. The AI feedback showed me exactly what was wrong with my writing structure. Got CLB 9 on my next try.',
      name: 'Priya S.',
      location: 'Toronto',
      clb: 'CLB 7 → 9',
      initials: 'PS',
      color: '#6366f1',
    },
    {
      quote: 'Saved me from paying $80/hour for a tutor. The speaking coach caught pronunciation issues I didn\'t even know I had.',
      name: 'Marco L.',
      location: 'Vancouver',
      clb: 'CLB 8 → 10',
      initials: 'ML',
      color: '#10b981',
    },
    {
      quote: 'The mock exam CLB estimate was spot-on. I knew I was ready before spending $300 on the real test.',
      name: 'Ahmed K.',
      location: 'Calgary',
      clb: 'CLB 9',
      initials: 'AK',
      color: '#f59e0b',
    },
  ];

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map(f => ({
      '@type': 'Question',
      name: f.q,
      acceptedAnswer: { '@type': 'Answer', text: f.a },
    })),
  };

  return (
    <main className={styles.home}>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      {/* ─── Hero Section ─── */}
      <section className={styles.hero}>
        <div className={styles.heroContent}>
          <div className={styles.badge}>
            <Sparkles size={14} />
            <span>🇨🇦 #1 AI-Powered CELPIP Prep</span>
          </div>

          <h1 className={styles.title}>
            Score <span className={styles.titleAccent}>9+ on CELPIP</span>
            <br />In Just 30 Days
          </h1>

          <p className={styles.subtitle}>
            AI coaches your Writing & Speaking in real-time. Know your weak spots. Fix them before test day.
          </p>

          <div className={styles.heroCtas}>
            <Link href="/onboarding" className={styles.ctaPrimary}>
              <span>Start Free Practice Now</span>
              <ArrowRight size={20} />
            </Link>
          </div>

          <div className={styles.heroTrust}>
            <div className={styles.trustItem}>
              <CheckCircle2 size={16} />
              <span>No credit card needed</span>
            </div>
            <div className={styles.trustItem}>
              <Users size={16} />
              <span>150+ students practicing</span>
            </div>
            <div className={styles.trustItem}>
              <Shield size={16} />
              <span>3,900+ exercises available</span>
            </div>
          </div>

          {/* Star rating */}
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', marginTop: '0.75rem', opacity: 0.85 }}>
            <span style={{ color: '#f59e0b', fontSize: '1.1rem', letterSpacing: 2 }}>★★★★★</span>
            <span style={{ color: 'rgba(255,255,255,0.6)', fontSize: '0.85rem' }}>Loved by CELPIP students across Canada</span>
          </div>
        </div>
      </section>

      {/* ─── Stats Bar ─── */}
      <section className={styles.statsBar}>
        {stats.map((stat, i) => (
          <div key={i} className={styles.statItem}>
            <span className={styles.statValue}>{stat.value}</span>
            <span className={styles.statLabel}>{stat.label}</span>
            <span className={styles.statSub}>{stat.sub}</span>
          </div>
        ))}
      </section>

      {/* ─── Social Proof / Testimonials ─── */}
      <section className={styles.testimonialsSection}>
        <div className={styles.sectionHeader}>
          <div className={styles.socialProofBadge}>
            <Users size={16} />
            <span>Join 500+ students preparing for CELPIP</span>
          </div>
          <h2>Real Results From Real Students</h2>
          <p>See how AI feedback helped them break through their CLB plateau.</p>
        </div>

        <div className={styles.testimonialsGrid}>
          {testimonials.map((t, i) => (
            <div key={i} className={styles.testimonialCard}>
              <div className={styles.testimonialQuote}>
                <Quote size={20} className={styles.quoteIcon} />
                <p>{t.quote}</p>
              </div>
              <div className={styles.testimonialAuthor}>
                <div className={styles.testimonialAuthorLeft}>
                  <div 
                    className={styles.testimonialAvatar}
                    style={{ background: t.color }}
                  >
                    {t.initials}
                  </div>
                  <div className={styles.testimonialInfo}>
                    <span className={styles.testimonialName}>{t.name}</span>
                    <span className={styles.testimonialLocation}>{t.location}</span>
                  </div>
                </div>
                <span className={styles.testimonialCLB}>{t.clb}</span>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ─── Urgency Banner ─── */}
      <section className={styles.urgencySection}>
        <div className={styles.urgencyContent}>
          <AlertTriangle size={20} />
          <div>
            <strong>Express Entry Draws Happen Every 2 Weeks</strong>
            <p>Every draw you miss is months of waiting. Every re-test is another $300. Is your CLB ready? Start practicing now — it&apos;s free.</p>
          </div>
          <Link href="/writing/task-1" className={styles.urgencyCta}>
            <span>Start Now</span>
            <ArrowRight size={16} />
          </Link>
        </div>
      </section>

      {/* ─── Skills Grid ─── */}
      <section className={styles.skillsSection}>
        <div className={styles.sectionHeader}>
          <h2>Practice All 4 CELPIP Skills</h2>
          <p>AI-powered exercises for every section of the exam</p>
        </div>

        <div className={styles.skillsGrid}>
          {skills.map((skill) => {
            const IconComponent = skill.icon;
            return (
              <Link 
                key={skill.id}
                href={skill.path}
                onClick={(e) => handleSkillClick(e, skill.path)}
                className={`${styles.skillCard} ${styles[skill.id]}`}
              >
                <div className={styles.skillIcon}>
                  <IconComponent size={28} strokeWidth={2} />
                </div>
                <h3>{skill.title}</h3>
                <p className={styles.skillStats}>{skill.stats}</p>
              </Link>
            );
          })}
        </div>
      </section>

      {/* ─── Pro Features ─── */}
      <section className={styles.proSection}>
        <div className={styles.sectionHeader}>
          <div className={styles.proBadge}>
            <Zap size={16} />
            <span>PRO</span>
          </div>
          <h2>Supercharge Your Prep With AI</h2>
          <p>Go beyond static practice. Our AI coach adapts to you, finds your weaknesses, and helps you improve faster.</p>
        </div>

        <div className={styles.proGrid}>
          {proFeatures.map((feature, i) => {
            const IconComp = feature.icon;
            return (
              <div key={i} className={styles.proCard}>
                <div className={styles.proCardIcon}>
                  <IconComp size={22} />
                </div>
                <h3>{feature.title}</h3>
                <p>{feature.desc}</p>
              </div>
            );
          })}
        </div>

        <div className={styles.proCtaWrapper}>
          <Link href="/dashboard" className={styles.ctaPrimary}>
            <span>Start Practicing Free</span>
            <ArrowRight size={20} />
          </Link>
          <p className={styles.proCtaSub}>3 free exercises daily. Pro: CA$29.99/month or CA$149.99/year. Cancel anytime.</p>
        </div>
      </section>

      {/* ─── Comparison Table ─── */}
      <section className={styles.comparisonSection}>
        <div className={styles.sectionHeader}>
          <h2>How We Compare</h2>
          <p>See why students are switching to CELPIP AI Coach</p>
        </div>

        <div className={styles.comparisonTable}>
          <div className={`${styles.compRow} ${styles.compHeader}`}>
            <div className={styles.compFeature}>Feature</div>
            <div className={styles.compUs}>CELPIP AI Coach</div>
            <div className={styles.compThem}>Other Platforms</div>
          </div>
          {comparisons.map((row, i) => (
            <div key={i} className={styles.compRow}>
              <div className={styles.compFeature}>{row.feature}</div>
              <div className={`${styles.compUs} ${styles.compHighlight}`}>{row.us}</div>
              <div className={styles.compThem}>{row.them}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ─── FAQ ─── */}
      <section className={styles.faqSection}>
        <div className={styles.sectionHeader}>
          <h2>Frequently Asked Questions</h2>
        </div>

        <div className={styles.faqList}>
          {faqs.map((faq, i) => (
            <div 
              key={i} 
              className={`${styles.faqItem} ${openFaq === i ? styles.faqOpen : ''}`}
              onClick={() => setOpenFaq(openFaq === i ? null : i)}
            >
              <div className={styles.faqQuestion}>
                <span>{faq.q}</span>
                <ChevronDown size={20} className={styles.faqChevron} />
              </div>
              <div className={styles.faqAnswer}>
                <p>{faq.a}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ─── Free Tools ─── */}
      <section className={styles.skillsSection}>
        <div className={styles.sectionHeader}>
          <h2>Free CELPIP Tools</h2>
          <p>No signup required. Use these tools to prepare smarter.</p>
        </div>
        <div className={styles.heroCtas} style={{ marginTop: 0 }}>
          <Link href="/tools/score-calculator" className={styles.ctaSecondary}>
            <span>🧮 CRS Score Calculator</span>
          </Link>
          <Link href="/tools/practice-timer" className={styles.ctaSecondary}>
            <span>⏱️ Practice Timer</span>
          </Link>
        </div>
      </section>

      {/* ─── Final CTA ─── */}
      <section className={styles.finalCta}>
        <div className={styles.finalCtaContent}>
          <h2>What Costs More — $8/month or Another $300 Re-test?</h2>
          <p>One failed CELPIP test costs $300 + months of immigration delay. AI feedback helps you pass the first time.</p>
          <div className={styles.heroCtas}>
            <Link href="/writing/task-1" className={styles.ctaPrimary}>
              <span>Start Practicing Free</span>
              <ArrowRight size={20} />
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}
