'use client';

import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { 
  Sparkles, PenLine, Mic, BookOpen, Headphones,
  ArrowRight, Zap, Target, TrendingUp, CheckCircle2,
  Brain, Clock, BarChart3, Shield, Users,
  ChevronDown, Globe, Award, Quote, AlertTriangle
} from 'lucide-react';
import EmailCapturePopup from '@/components/EmailCapturePopup';
import styles from '@/styles/Home.module.scss';

export default function HomePage() {
  const [mounted, setMounted] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  useEffect(() => {
    setMounted(true);
  }, []);

  const skills = [
    {
      id: 'writing',
      title: 'Writing',
      desc: 'Email & Survey responses with real-time AI scoring on the 1-12 CELPIP scale',
      icon: PenLine,
      stats: '75+ prompts • AI Scoring',
      path: '/writing',
      free: '42 Task 1 + 33 Task 2 prompts'
    },
    {
      id: 'speaking',
      title: 'Speaking',
      desc: 'Record yourself, get instant AI analysis with pronunciation & fluency feedback',
      icon: Mic,
      stats: '8 Tasks • Whisper AI',
      path: '/speaking',
      free: '24 prompts + self-eval checklist'
    },
    {
      id: 'reading',
      title: 'Reading',
      desc: 'Timed passages with authentic exam-style questions across all 4 parts',
      icon: BookOpen,
      stats: '4 Parts • 17 Passages',
      path: '/reading',
      free: '17 full passages, 100% free'
    },
    {
      id: 'listening',
      title: 'Listening',
      desc: 'One-play audio — just like the real CELPIP test, with 24 practice passages',
      icon: Headphones,
      stats: '6 Parts • 24 Passages',
      path: '/listening',
      free: '24 passages + cached audio'
    }
  ];

  const proFeatures = [
    { icon: Brain, title: 'AI Practice Generator', desc: 'Infinite exercises generated by AI, tailored to your level' },
    { icon: TrendingUp, title: 'Adaptive Difficulty', desc: 'Auto-adjusts based on your performance — always in your growth zone' },
    { icon: PenLine, title: 'AI Writing Tutor', desc: 'Detailed grammar, vocabulary & structure feedback on every response' },
    { icon: Mic, title: 'AI Speaking Coach', desc: 'Whisper transcription + GPT analysis of pronunciation, fluency & coherence' },
    { icon: Target, title: 'AI Mock Exam', desc: 'Full simulated CELPIP test with timer, scoring & CLB estimate' },
    { icon: BarChart3, title: 'Weakness Report', desc: 'Per-section breakdown with trends and personalized recommendations' },
  ];

  const comparisons = [
    { feature: 'Practice Questions', us: '200+ (infinite with AI)', them: 'Fixed question banks' },
    { feature: 'AI Feedback', us: 'Real-time on Writing & Speaking', them: 'Answer keys only' },
    { feature: 'Adaptive Difficulty', us: '✅ Auto-adjusts to your level', them: '❌ One size fits all' },
    { feature: 'Mock Exam with CLB Estimate', us: '✅ Full simulation', them: '❌ or basic only' },
    { feature: 'Audio Listening Practice', us: '24 cached + unlimited AI', them: 'Limited passages' },
    { feature: 'Price', us: 'Free tier + CA$24.99/mo Pro', them: '$29-49/month, no free tier' },
  ];

  const faqs = [
    { q: 'Is there really free content?', a: 'Yes! All 24 listening passages with audio, 17 reading passages, 75+ writing prompts, 24 speaking prompts, technique guides, and quizzes are completely free. No credit card needed.' },
    { q: 'What does Pro include?', a: 'Pro unlocks AI-powered features: infinite practice exercises, AI Writing Tutor with detailed feedback, AI Speaking Coach with Whisper transcription, Mock Exams with CLB estimates, adaptive difficulty, and weakness reports.' },
    { q: 'Can I cancel anytime?', a: 'Absolutely. Cancel your Pro subscription anytime from your profile. No contracts, no hidden fees. You keep access until the end of your billing period.' },
    { q: 'How is this different from other CELPIP prep sites?', a: 'Most sites offer static question banks. We use AI to generate infinite exercises, give real-time feedback on writing and speaking, and adapt difficulty to your level. Plus our free tier is more generous than competitors\' paid plans.' },
    { q: 'Does it work on mobile?', a: 'Yes! The entire platform is mobile-optimized. Practice on your phone during commute, lunch breaks, or anywhere.' },
    { q: 'I\'m taking CELPIP next week. Can this help?', a: 'Definitely. Start with our Technique Guides for quick strategy tips, then do a Mock Exam to identify weak areas. Even a few days of focused AI practice can improve your score.' },
  ];

  const stats = [
    { value: '24', label: 'Listening Passages', sub: 'with audio' },
    { value: '17', label: 'Reading Passages', sub: 'all parts' },
    { value: '75+', label: 'Writing Prompts', sub: 'Task 1 & 2' },
    { value: '∞', label: 'AI Exercises', sub: 'Pro feature' },
  ];

  const testimonials = [
    {
      quote: 'I was stuck at CLB 7 for 3 tests. The AI feedback showed me exactly what was wrong with my writing structure. Got CLB 9 on my next try.',
      name: 'Priya S.',
      location: 'Toronto',
      clb: 'CLB 7 → 9',
    },
    {
      quote: 'Saved me from paying $80/hour for a tutor. The speaking coach caught pronunciation issues I didn\'t even know I had.',
      name: 'Marco L.',
      location: 'Vancouver',
      clb: 'CLB 8 → 10',
    },
    {
      quote: 'The mock exam CLB estimate was spot-on. I knew I was ready before spending $300 on the real test.',
      name: 'Ahmed K.',
      location: 'Calgary',
      clb: 'CLB 9',
    },
  ];

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map(f => ({
      '@type': 'Question',
      name: f.q,
      acceptedAnswer: { '@type': 'Answer', text: f.a },
    })),
  };

  return (
    <main className={styles.home}>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <EmailCapturePopup />
      {/* ─── Hero Section ─── */}
      <section className={styles.hero}>
        <div className={styles.heroContent}>
          <div className={styles.badge}>
            <Sparkles size={14} />
            <span>🇨🇦 #1 AI-Powered CELPIP Prep Platform</span>
          </div>

          <h1 className={styles.title}>
            Stop Retaking CELPIP.
            <span className={styles.titleAccent}> Pass It The First Time.</span>
          </h1>

          <p className={styles.subtitle}>
            Free AI coaching that tells you exactly what to fix in your Writing and Speaking — so you stop wasting $300 on re-tests. Used by students targeting CLB 7-12.
          </p>

          <div className={styles.heroCtas}>
            <Link href="/writing/task-1" className={styles.ctaPrimary}>
              <span>Start Practicing Free</span>
              <ArrowRight size={20} />
            </Link>
            <Link href="/pricing" className={styles.ctaSecondary}>
              <span>See Pro Features</span>
            </Link>
          </div>

          <div className={styles.heroTrust}>
            <div className={styles.trustItem}>
              <CheckCircle2 size={16} />
              <span>No credit card required</span>
            </div>
            <div className={styles.trustItem}>
              <CheckCircle2 size={16} />
              <span>200+ free practice exercises</span>
            </div>
            <div className={styles.trustItem}>
              <CheckCircle2 size={16} />
              <span>Built for Canadian immigration</span>
            </div>
          </div>
        </div>
      </section>

      {/* ─── Stats Bar ─── */}
      <section className={styles.statsBar}>
        {stats.map((stat, i) => (
          <div key={i} className={styles.statItem}>
            <span className={styles.statValue}>{stat.value}</span>
            <span className={styles.statLabel}>{stat.label}</span>
            <span className={styles.statSub}>{stat.sub}</span>
          </div>
        ))}
      </section>

      {/* ─── Social Proof / Testimonials ─── */}
      <section className={styles.testimonialsSection}>
        <div className={styles.sectionHeader}>
          <div className={styles.socialProofBadge}>
            <Users size={16} />
            <span>Join 500+ students preparing for CELPIP</span>
          </div>
          <h2>Real Results From Real Students</h2>
          <p>See how AI feedback helped them break through their CLB plateau.</p>
        </div>

        <div className={styles.testimonialsGrid}>
          {testimonials.map((t, i) => (
            <div key={i} className={styles.testimonialCard}>
              <div className={styles.testimonialQuote}>
                <Quote size={20} className={styles.quoteIcon} />
                <p>{t.quote}</p>
              </div>
              <div className={styles.testimonialAuthor}>
                <div className={styles.testimonialInfo}>
                  <span className={styles.testimonialName}>{t.name}</span>
                  <span className={styles.testimonialLocation}>{t.location}</span>
                </div>
                <span className={styles.testimonialCLB}>{t.clb}</span>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ─── Urgency Banner ─── */}
      <section className={styles.urgencySection}>
        <div className={styles.urgencyContent}>
          <AlertTriangle size={20} />
          <div>
            <strong>Your CELPIP Test Is Coming</strong>
            <p>Every week you wait is another week without your PR. Every re-test is another $300. Start practicing now — it&apos;s free.</p>
          </div>
          <Link href="/writing/task-1" className={styles.urgencyCta}>
            <span>Start Now</span>
            <ArrowRight size={16} />
          </Link>
        </div>
      </section>

      {/* ─── Skills Grid ─── */}
      <section className={styles.skillsSection}>
        <div className={styles.sectionHeader}>
          <h2>Practice All 4 CELPIP Modules</h2>
          <p>Comprehensive content for every section of the exam — most of it completely free.</p>
        </div>

        <div className={styles.skillsGrid}>
          {skills.map((skill, index) => {
            const IconComponent = skill.icon;
            return (
              <Link 
                key={skill.id}
                href={skill.path}
                className={styles.skillCard}
                style={{ '--delay': `${index * 80}ms` } as React.CSSProperties}
              >
                <div className={`${styles.skillIcon} ${styles[skill.id]}`}>
                  <IconComponent size={24} strokeWidth={2} />
                </div>
                
                <div className={styles.skillContent}>
                  <h3>{skill.title}</h3>
                  <p>{skill.desc}</p>
                  <span className={styles.skillStats}>{skill.stats}</span>
                  <span className={styles.skillFree}>🆓 {skill.free}</span>
                </div>

                <div className={styles.skillArrow}>
                  <ArrowRight size={18} />
                </div>
              </Link>
            );
          })}
        </div>
      </section>

      {/* ─── Pro Features ─── */}
      <section className={styles.proSection}>
        <div className={styles.sectionHeader}>
          <div className={styles.proBadge}>
            <Zap size={16} />
            <span>PRO</span>
          </div>
          <h2>Supercharge Your Prep With AI</h2>
          <p>Go beyond static practice. Our AI coach adapts to you, finds your weaknesses, and helps you improve faster.</p>
        </div>

        <div className={styles.proGrid}>
          {proFeatures.map((feature, i) => {
            const IconComp = feature.icon;
            return (
              <div key={i} className={styles.proCard}>
                <div className={styles.proCardIcon}>
                  <IconComp size={22} />
                </div>
                <h3>{feature.title}</h3>
                <p>{feature.desc}</p>
              </div>
            );
          })}
        </div>

        <div className={styles.proCtaWrapper}>
          <Link href="/pricing" className={styles.ctaPrimary}>
            <span>Start 3-Day Free Trial</span>
            <ArrowRight size={20} />
          </Link>
          <p className={styles.proCtaSub}>No charge for 3 days. Then CA$24.99/month or CA$99/year. Cancel anytime.</p>
        </div>
      </section>

      {/* ─── Comparison Table ─── */}
      <section className={styles.comparisonSection}>
        <div className={styles.sectionHeader}>
          <h2>How We Compare</h2>
          <p>See why students are switching to CELPIP AI Coach</p>
        </div>

        <div className={styles.comparisonTable}>
          <div className={`${styles.compRow} ${styles.compHeader}`}>
            <div className={styles.compFeature}>Feature</div>
            <div className={styles.compUs}>CELPIP AI Coach</div>
            <div className={styles.compThem}>Other Platforms</div>
          </div>
          {comparisons.map((row, i) => (
            <div key={i} className={styles.compRow}>
              <div className={styles.compFeature}>{row.feature}</div>
              <div className={`${styles.compUs} ${styles.compHighlight}`}>{row.us}</div>
              <div className={styles.compThem}>{row.them}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ─── FAQ ─── */}
      <section className={styles.faqSection}>
        <div className={styles.sectionHeader}>
          <h2>Frequently Asked Questions</h2>
        </div>

        <div className={styles.faqList}>
          {faqs.map((faq, i) => (
            <div 
              key={i} 
              className={`${styles.faqItem} ${openFaq === i ? styles.faqOpen : ''}`}
              onClick={() => setOpenFaq(openFaq === i ? null : i)}
            >
              <div className={styles.faqQuestion}>
                <span>{faq.q}</span>
                <ChevronDown size={20} className={styles.faqChevron} />
              </div>
              <div className={styles.faqAnswer}>
                <p>{faq.a}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ─── Free Tools ─── */}
      <section className={styles.skillsSection}>
        <div className={styles.sectionHeader}>
          <h2>Free CELPIP Tools</h2>
          <p>No signup required. Use these tools to prepare smarter.</p>
        </div>
        <div className={styles.heroCtas} style={{ marginTop: 0 }}>
          <Link href="/tools/score-calculator" className={styles.ctaSecondary}>
            <span>🧮 CRS Score Calculator</span>
          </Link>
          <Link href="/tools/practice-timer" className={styles.ctaSecondary}>
            <span>⏱️ Practice Timer</span>
          </Link>
        </div>
      </section>

      {/* ─── Final CTA ─── */}
      <section className={styles.finalCta}>
        <div className={styles.finalCtaContent}>
          <h2>What Costs More — $8/month or Another $300 Re-test?</h2>
          <p>One failed CELPIP test costs $300 + months of immigration delay. AI feedback helps you pass the first time.</p>
          <div className={styles.heroCtas}>
            <Link href="/writing/task-1" className={styles.ctaPrimary}>
              <span>Start Practicing Free</span>
              <ArrowRight size={20} />
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}
